/**
 * The tuning catalog — 67 tunings.
 *
 * GENERATED by scripts/build-tunings.mjs. Edit that script (or the curated
 * block inside it) rather than this file.
 *
 * `midi` runs LOW STRING FIRST: index 0 is the string drawn at the bottom of
 * the fretboard (string 6 on a guitar, string 10 on a pedal steel). Values are
 * MIDI note numbers, so C4 = middle C = 60, pitch class = midi % 12.
 *
 * Sources: lap-steel and open-major stacks curated and cross-checked against
 * John Ely's master list, Peterson tuner presets, papadafoe.com, steelc6th.com
 * and the Steel Guitar Forum; everything else from the VG-800 tuner catalog
 * (github.com/fxcircus/vg800_midi_control).
 */

export type TuningGroup =
  | 'lap-steel'
  | 'open'
  | 'common'
  | 'drop'
  | 'artist'
  | 'mode'
  | 'world'
  | 'pedal-steel';

export interface Tuning {
  id: string;
  name: string;
  group: TuningGroup;
  /** MIDI note numbers, low string first. 3–10 entries. */
  midi: number[];
  /** Display spellings matching `midi`, low string first. */
  spellings: string[];
  /** One-line musician answer to "why would I pick this?" */
  description?: string;
  /** A signature recording in this tuning. */
  song?: string;
  /**
   * The key this tuning implies, when the open-stack chord derivation
   * (see keyFromTuning.ts) would get it wrong. Scale is a SCALE_INTERVALS name.
   */
  key?: { root: string; scale: string };
  /** Which pedal-steel copedent this neck carries (see copedents.ts). */
  copedent?: 'e9' | 'c6';
  /** Stack does not ascend — high-strung, re-entrant, or octave-doubled. */
  reentrant?: boolean;
  /** Read this tuning in flats (its own spelling is flat-leaning). */
  preferFlats?: boolean;
}

export const TUNINGS: Tuning[] = [
  {
    id: "c6",
    name: "C6",
    group: "lap-steel",
    midi: [48, 52, 55, 57, 60, 64],
    spellings: ["C", "E", "G", "A", "C", "E"],
    description:
      "The lap steel standard (Jerry Byrd). One bar = C major on the low strings, its relative A minor on top — a major chord and its relative minor under every fret.",
  },
  {
    id: "a6",
    name: "A6",
    group: "lap-steel",
    midi: [49, 52, 54, 57, 61, 64],
    spellings: ["C♯", "E", "F♯", "A", "C♯", "E"],
    description:
      "The classic western swing tuning — the same 6th-chord sound as C6, voiced with the 3rd in the bass: A major on the top three strings, F♯m just below.",
  },
  {
    id: "c6-a7",
    name: "C6/A7",
    group: "lap-steel",
    midi: [49, 52, 55, 57, 60, 64],
    spellings: ["C♯", "E", "G", "A", "C", "E"],
    description:
      "C6 with the low C raised to C♯ — the top four strings keep C6, the bottom four spell A7. Sixth and dominant worlds under one bar (Jerry Byrd).",
    key: { root: "C", scale: "Major" },
  },
  {
    id: "e7",
    name: "E7",
    group: "lap-steel",
    midi: [47, 50, 52, 56, 59, 64],
    spellings: ["B", "D", "E", "G♯", "B", "E"],
    description:
      "The blues standard — a dominant 7th built in, while the top four strings stay a pure E major triad.",
  },
  {
    id: "e13",
    name: "E13",
    group: "lap-steel",
    midi: [50, 52, 56, 59, 61, 64],
    spellings: ["D", "E", "G♯", "B", "C♯", "E"],
    description:
      "Pre-pedal country. E7 plus the 13th (C♯) — crying parallel 6ths on top, the G♯–D tritone pull built in.",
  },
  {
    id: "e9-lap",
    name: "E9 (lap)",
    group: "lap-steel",
    midi: [50, 52, 54, 56, 59, 64],
    spellings: ["D", "E", "F♯", "G♯", "B", "E"],
    description:
      "A dominant-9th color tuning — ♭7, root and 9 stacked on the low strings for sultry blues colors. Not the pedal-steel E9.",
  },
  {
    id: "b11",
    name: "B11",
    group: "lap-steel",
    midi: [47, 51, 54, 57, 61, 64],
    spellings: ["B", "D♯", "F♯", "A", "C♯", "E"],
    description:
      "Jerry Byrd's Hawaiian specialty — B, F♯m, and A triads plus B7/B9 colors all under one straight bar, resolving a 4th up.",
  },
  {
    id: "b11-tk-smith",
    name: "B11 (T.K. Smith)",
    group: "lap-steel",
    midi: [47, 51, 54, 57, 61, 64],
    spellings: ["B", "D♯", "F♯", "A", "C♯", "E"],
    description:
      "T.K. Smith’s 6-string B11 (1·3·5·♭7·9·11 = B D♯ F♯ A C♯ E), his current setup on a 1934 Rickenbacher — B, F♯m and A triads plus B7/B9 colors under one straight bar.",
  },
  {
    id: "cyrus-hybrid",
    name: "Cyrus Hybrid",
    group: "lap-steel",
    midi: [43, 47, 50, 54, 57, 62],
    spellings: ["G", "B", "D", "F♯", "A", "D"],
    description:
      "Luke Cyrus Goetze’s G/D hybrid — G major on the low three strings, D major on the top three, so one bar covers both the I and the V. The open stack rings as a shimmering Gmaj9.",
  },
  {
    id: "open-e",
    name: "Open E",
    group: "open",
    midi: [40, 47, 52, 56, 59, 64],
    spellings: ["E", "B", "E", "G♯", "B", "E"],
    description:
      "A straight major triad, same as bottleneck open E — blues-rock and sacred steel. The easiest entry point for guitar players.",
  },
  {
    id: "open-d",
    name: "Open D",
    group: "open",
    midi: [38, 45, 50, 54, 57, 62],
    spellings: ["D", "A", "D", "F♯", "A", "D"],
    description:
      "Open E a whole step down — old-time, gospel, and Weissenborn territory. Lower tension, darker voice.",
  },
  {
    id: "open-g-dobro",
    name: "Open G (Dobro)",
    group: "open",
    midi: [43, 47, 50, 55, 59, 62],
    spellings: ["G", "B", "D", "G", "B", "D"],
    description:
      "Two stacked G triads (G-B-D twice) — the bluegrass and resonator standard, built for harmonized melody in 3rds.",
  },
  {
    id: "open-g-low",
    name: "Open G (low bass)",
    group: "open",
    midi: [38, 43, 50, 55, 59, 62],
    spellings: ["D", "G", "D", "G", "B", "D"],
    description:
      "Guitar-style 'Spanish' open G — the same top four strings over a deep D-G bass pair.",
  },
  {
    id: "open-a-high",
    name: "Open A (high bass)",
    group: "open",
    midi: [45, 49, 52, 57, 61, 64],
    spellings: ["A", "C♯", "E", "A", "C♯", "E"],
    description:
      "The classic 1920s Hawaiian tuning (Sol Hoopii) — the Dobro-G shape a whole step up, bright and singing.",
  },
  {
    id: "standard",
    name: "Standard",
    group: "common",
    midi: [40, 45, 50, 55, 59, 64],
    spellings: ["E", "A", "D", "G", "B", "E"],
    key: { root: "E", scale: "Minor" },
  },
  {
    id: "dadgad",
    name: "DADGAD",
    group: "common",
    midi: [38, 45, 50, 55, 57, 62],
    spellings: ["D", "A", "D", "G", "A", "D"],
    description:
      "Modal \"Celtic\" tuning — the open strings ring a Dsus4. Pioneered by Davey Graham.",
    song: "\"She Moved Through the Fair\" — Davey Graham",
    key: { root: "D", scale: "Mixolydian" },
  },
  {
    id: "nashville",
    name: "Nashville",
    group: "common",
    midi: [52, 57, 62, 67, 59, 64],
    spellings: ["E", "A", "D", "G", "B", "E"],
    description:
      "\"High-strung\" — the lower four strings swap to light gauges an octave up for a shimmering, 12-string-like chime. A studio doubling trick.",
    song: "\"Wild Horses\" — The Rolling Stones",
    key: { root: "E", scale: "Minor" },
    reentrant: true,
  },
  {
    id: "baritone",
    name: "Baritone",
    group: "common",
    midi: [35, 40, 45, 50, 54, 59],
    spellings: ["B", "E", "A", "D", "F♯", "B"],
    description:
      "A long-scale guitar tuned a fourth low (B to B); born in surf and spaghetti-western scores.",
    song: "\"Wichita Lineman\" — Glen Campbell",
    key: { root: "B", scale: "Minor" },
  },
  {
    id: "bass-vi",
    name: "Bass VI",
    group: "common",
    midi: [28, 33, 38, 43, 47, 52],
    spellings: ["E", "A", "D", "G", "B", "E"],
    description:
      "The whole guitar dropped a full octave — the Fender Bass VI's baritone-bass register, between guitar and bass.",
    song: "\"Lullaby\" — The Cure",
    key: { root: "E", scale: "Minor" },
  },
  {
    id: "hendrix",
    name: "Hendrix",
    group: "common",
    midi: [39, 44, 49, 54, 58, 63],
    spellings: ["E♭", "A♭", "D♭", "G♭", "B♭", "E♭"],
    description:
      "Standard tuned down a half step to E♭ — slinkier strings and a darker, fatter tone. Jimi's default.",
    song: "\"Purple Haze\" — Jimi Hendrix",
    key: { root: "E♭", scale: "Minor" },
    preferFlats: true,
  },
  {
    id: "drop-d",
    name: "Drop D",
    group: "drop",
    midi: [38, 45, 50, 55, 59, 64],
    spellings: ["D", "A", "D", "G", "B", "E"],
    description:
      "The low string dropped a whole step for one-finger power chords and a heavier low end.",
    song: "\"Everlong\" — Foo Fighters",
    key: { root: "D", scale: "Major" },
  },
  {
    id: "drop-db",
    name: "Drop Db",
    group: "drop",
    midi: [37, 44, 49, 54, 58, 63],
    spellings: ["D♭", "A♭", "D♭", "G♭", "B♭", "E♭"],
    description:
      "Drop D shifted down a half step (Drop C#) for extra weight while staying playable.",
    song: "\"Them Bones\" — Alice in Chains",
    key: { root: "C♯", scale: "Minor" },
    preferFlats: true,
  },
  {
    id: "drop-c",
    name: "Drop C",
    group: "drop",
    midi: [36, 43, 48, 53, 57, 62],
    spellings: ["C", "G", "C", "F", "A", "D"],
    description:
      "Drop D down a whole step — a huge nu-metal/metalcore rhythm tuning.",
    song: "\"Chop Suey!\" — System of a Down",
    key: { root: "C", scale: "Minor" },
  },
  {
    id: "drop-b",
    name: "Drop B",
    group: "drop",
    midi: [35, 42, 47, 52, 56, 61],
    spellings: ["B", "G♭", "B", "E", "A♭", "D♭"],
    description:
      "Drop D down a minor third — heavy, tight and modern.",
    song: "\"Duality\" — Slipknot",
    key: { root: "B", scale: "Minor" },
    preferFlats: true,
  },
  {
    id: "drop-bb",
    name: "Drop Bb",
    group: "drop",
    midi: [34, 41, 46, 51, 55, 60],
    spellings: ["B♭", "F", "B♭", "E♭", "G", "C"],
    description:
      "Drop D down a fourth (Drop A#) for a crushing low register.",
    song: "\"Shadow Moses\" — Bring Me The Horizon",
    key: { root: "B♭", scale: "Minor" },
    preferFlats: true,
  },
  {
    id: "drop-a",
    name: "Drop A",
    group: "drop",
    midi: [33, 40, 45, 50, 54, 59],
    spellings: ["A", "E", "A", "D", "F♯", "B"],
    description:
      "The low string down a fourth then dropped — a metalcore/deathcore staple.",
    song: "\"Psychosocial\" — Slipknot",
    key: { root: "A", scale: "Minor" },
  },
  {
    id: "fripp-nst",
    name: "Fripp NST",
    group: "artist",
    midi: [36, 43, 50, 57, 64, 67],
    spellings: ["C", "G", "D", "A", "E", "G"],
    description:
      "Robert Fripp's New Standard Tuning — all fifths (plus a top minor third), built for wide, ringing intervals.",
    song: "\"Frame by Frame\" — King Crimson",
  },
  {
    id: "gambale",
    name: "Gambale",
    group: "artist",
    midi: [45, 50, 55, 60, 52, 57],
    spellings: ["A", "D", "G", "C", "E", "A"],
    description:
      "Frank Gambale's tuning — the whole guitar up a fourth with the top two strings dropped an octave, so standard shapes yield piano-like close voicings. Invented for his own fusion playing.",
    key: { root: "A", scale: "Minor" },
    reentrant: true,
  },
  {
    id: "led-kashmir",
    name: "Led Kashmir",
    group: "artist",
    midi: [38, 45, 50, 55, 57, 62],
    spellings: ["D", "A", "D", "G", "A", "D"],
    description:
      "Led Zeppelin · “Kashmir” (Jimmy Page, on his Danelectro)",
    key: { root: "D", scale: "Mixolydian" },
  },
  {
    id: "led-rain",
    name: "Led Rain",
    group: "artist",
    midi: [38, 43, 48, 55, 60, 62],
    spellings: ["D", "G", "C", "G", "C", "D"],
    description:
      "Jimmy Page's lush DADGAD variation (a Gsus4/D voicing), written for one specific song.",
    song: "\"The Rain Song\" — Led Zeppelin",
    key: { root: "G", scale: "Major" },
  },
  {
    id: "blur-song2",
    name: "Blur Song2",
    group: "artist",
    midi: [38, 45, 50, 55, 59, 64],
    spellings: ["D", "A", "D", "G", "B", "E"],
    description:
      "Drop D grunge-pop — the low string falls a whole step for the woo-hoo riff's punch.",
    song: "\"Song 2\" — Blur",
    key: { root: "D", scale: "Major" },
  },
  {
    id: "schizophrenia",
    name: "Schizophrenia",
    group: "artist",
    midi: [42, 42, 55, 55, 57, 69],
    spellings: ["F♯", "F♯", "G", "G", "A", "A"],
    description:
      "Thurston Moore's clustered Sonic Youth drone tuning — three adjacent scale tones doubled, with no clear root.",
    song: "\"Schizophrenia\" — Sonic Youth",
    key: { root: "G", scale: "Major" },
  },
  {
    id: "nick-drake",
    name: "Nick Drake",
    group: "artist",
    midi: [36, 43, 48, 53, 60, 64],
    spellings: ["C", "G", "C", "F", "C", "E"],
    description:
      "One of Nick Drake's signature open-C-based tunings (capo 2 on the record) — a wide, resonant shimmer.",
    song: "\"Pink Moon\" — Nick Drake",
  },
  {
    id: "keith-richards",
    name: "Keith Richards",
    group: "artist",
    midi: [43, 43, 50, 55, 59, 62],
    spellings: ["G", "G", "D", "G", "B", "D"],
    description:
      "Keith's trademark — open G with the low string removed, played on a 5-string.",
    song: "\"Start Me Up\" — The Rolling Stones",
  },
  {
    id: "am-football",
    name: "Am. Football",
    group: "artist",
    midi: [41, 45, 48, 55, 60, 64],
    spellings: ["F", "A", "C", "G", "C", "E"],
    description:
      "American Football's open-F(maj9) emo/math-rock tuning — the whole opening line falls under one finger.",
    song: "\"Never Meant\" — American Football",
  },
  {
    id: "soundg-wave",
    name: "SoundG Wave",
    group: "artist",
    midi: [40, 40, 47, 59, 59, 59],
    spellings: ["E", "E", "B", "B", "B", "B"],
    description:
      "Chris Cornell & Kim Thayil's drone tuning — often written EEBBBB, but Thayil says it's really EEBBBE.",
    song: "\"My Wave\" — Soundgarden",
  },
  {
    id: "soundg-sun",
    name: "SoundG Sun",
    group: "artist",
    midi: [38, 45, 50, 55, 59, 64],
    spellings: ["D", "A", "D", "G", "B", "E"],
    description:
      "Drop D — the low string falls a whole step; the swaying Leslie-swirl chords ride over it.",
    song: "\"Black Hole Sun\" — Soundgarden",
    key: { root: "D", scale: "Major" },
  },
  {
    id: "young-cinnamon",
    name: "Young Cinnamon",
    group: "artist",
    midi: [38, 45, 50, 55, 59, 64],
    spellings: ["D", "A", "D", "G", "B", "E"],
    description:
      "Neil Young's crunch tuning — the low string drops a whole step for the riff's growl.",
    song: "\"Cinnamon Girl\" — Neil Young",
    key: { root: "D", scale: "Major" },
  },
  {
    id: "joni-cab",
    name: "Joni Cab",
    group: "artist",
    midi: [40, 47, 52, 56, 59, 64],
    spellings: ["E", "B", "E", "G♯", "B", "E"],
    description:
      "Joni built her sound on personal open tunings, described by bass note plus fret offsets (her catalog uses 50+).",
    song: "\"Big Yellow Taxi\" — Joni Mitchell",
  },
  {
    id: "joni-sides",
    name: "Joni Sides",
    group: "artist",
    midi: [38, 45, 50, 54, 57, 62],
    spellings: ["D", "A", "D", "F♯", "A", "D"],
    description:
      "Joni's open-D base — a Dmaj7 rings on the open strings. On the record she capos 4 (sounding F# major); this is the no-capo tuning.",
    song: "\"Both Sides, Now\" — Joni Mitchell",
  },
  {
    id: "radio-pyramid",
    name: "Radio Pyramid",
    group: "artist",
    midi: [42, 46, 49, 54, 58, 66],
    spellings: ["F♯", "A♯", "C♯", "F♯", "A♯", "F♯"],
    description:
      "Open F# major — let the top F# ring as a pedal while barre shapes slide beneath for the song's swaying, ambiguous chords.",
    song: "\"Pyramid Song\" — Radiohead",
  },
  {
    id: "radio-everything",
    name: "Radio Everything",
    group: "artist",
    midi: [36, 43, 48, 55, 56, 60],
    spellings: ["C", "G", "C", "G", "G♯", "C"],
    description:
      "An \"Everything In Its Right Place\" voicing built around a C pedal on the top string (the same pedal-note trick as Pyramid Song's F#). Open strings ring C G C G G# C; hold the G → C bender to push the neutral G string up a fourth while the top C keeps ringing.",
    song: "\"Everything In Its Right Place\" — Radiohead",
    key: { root: "C", scale: "Phrygian" },
  },
  {
    id: "white-keys",
    name: "White Keys",
    group: "mode",
    midi: [48, 50, 52, 53, 55, 57],
    spellings: ["C", "D", "E", "F", "G", "A"],
    description:
      "The natural notes C D E F G A on six strings — the white-key set every mode is drawn from, with C on the low string as home. Identical to C Ionian.",
    key: { root: "C", scale: "Major" },
  },
  {
    id: "c-lydian",
    name: "C Lydian",
    group: "mode",
    midi: [48, 50, 52, 54, 55, 57],
    spellings: ["C", "D", "E", "F♯", "G", "A"],
    description:
      "The brightest mode — major with a raised 4th. Floating, film-score shimmer.",
    song: "\"Flying Theme\" — John Williams (E.T.)",
    key: { root: "C", scale: "Lydian" },
  },
  {
    id: "c-ionian",
    name: "C Ionian",
    group: "mode",
    midi: [48, 50, 52, 53, 55, 57],
    spellings: ["C", "D", "E", "F", "G", "A"],
    description:
      "The plain major scale — the mode that feels like home.",
    song: "\"Let It Be\" — The Beatles",
    key: { root: "C", scale: "Major" },
  },
  {
    id: "c-mixolydian",
    name: "C Mixolydian",
    group: "mode",
    midi: [48, 50, 52, 53, 55, 57],
    spellings: ["C", "D", "E", "F", "G", "A"],
    description:
      "Major with a flat 7th — the dominant, bluesy-rock colour. (The ♭7 has no open string in this set, so it shares the Ionian shape.)",
    song: "\"Sweet Home Alabama\" — Lynyrd Skynyrd",
    key: { root: "C", scale: "Mixolydian" },
  },
  {
    id: "c-dorian",
    name: "C Dorian",
    group: "mode",
    midi: [48, 50, 51, 53, 55, 57],
    spellings: ["C", "D", "E♭", "F", "G", "A"],
    description:
      "Minor with a bright natural 6th — the hopeful, funky minor of jazz and modal rock.",
    song: "\"So What\" — Miles Davis",
    key: { root: "C", scale: "Dorian" },
    preferFlats: true,
  },
  {
    id: "c-aeolian",
    name: "C Aeolian",
    group: "mode",
    midi: [48, 50, 51, 53, 55, 56],
    spellings: ["C", "D", "E♭", "F", "G", "A♭"],
    description:
      "The natural minor scale — ♭3 ♭6 ♭7. The default \"sad\" minor.",
    song: "\"Losing My Religion\" — R.E.M.",
    key: { root: "C", scale: "Minor" },
    preferFlats: true,
  },
  {
    id: "c-phrygian",
    name: "C Phrygian",
    group: "mode",
    midi: [48, 49, 51, 53, 55, 56],
    spellings: ["C", "D♭", "E♭", "F", "G", "A♭"],
    description:
      "Minor with a flat 2nd — dark, Spanish/flamenco and metal tension.",
    song: "\"Wherever I May Roam\" — Metallica",
    key: { root: "C", scale: "Phrygian" },
    preferFlats: true,
  },
  {
    id: "c-locrian",
    name: "C Locrian",
    group: "mode",
    midi: [48, 49, 51, 53, 54, 56],
    spellings: ["C", "D♭", "E♭", "F", "G♭", "A♭"],
    description:
      "The darkest mode — a flat 2nd AND flat 5th give an unstable, diminished tonic.",
    song: "\"YYZ\" — Rush (main riff)",
    key: { root: "C", scale: "Locrian" },
    preferFlats: true,
  },
  {
    id: "mandolin",
    name: "Mandolin",
    group: "world",
    midi: [55, 62, 69, 76],
    spellings: ["G", "D", "A", "E"],
    description:
      "Standard mandolin, tuned in fifths like a violin.",
    song: "\"Losing My Religion\" — R.E.M. (Peter Buck)",
    key: { root: "G", scale: "Major" },
  },
  {
    id: "irish-bouzouki",
    name: "Irish Bouzouki",
    group: "world",
    midi: [43, 50, 57, 62],
    spellings: ["G", "D", "A", "D"],
    description:
      "The Greek bouzouki adapted for Celtic music — flat-backed, tuned a fifth lower — as a rhythm and countermelody engine.",
    song: "Irish trad — Planxty (Andy Irvine & Dónal Lunny)",
    key: { root: "D", scale: "Major" },
  },
  {
    id: "greek-bouzouki",
    name: "Greek Bouzouki",
    group: "world",
    midi: [48, 53, 57, 62],
    spellings: ["C", "F", "A", "D"],
    description:
      "The bright, tremolo-driven lead of Greek rebetiko and laïkó.",
    song: "\"Zorba's Dance (Sirtaki)\" — Mikis Theodorakis",
    key: { root: "D", scale: "Minor" },
  },
  {
    id: "oud",
    name: "Oud",
    group: "world",
    midi: [36, 41, 45, 50, 55, 60],
    spellings: ["C", "F", "A", "D", "G", "C"],
    description:
      "The fretless lute at the heart of Arabic and Turkish maqam music (tuning varies by region and maqam).",
    song: "Arabic maqam tradition — e.g. Munir Bashir",
    key: { root: "C", scale: "Major" },
  },
  {
    id: "charango",
    name: "Charango",
    group: "world",
    midi: [55, 60, 64, 69, 76],
    spellings: ["G", "C", "E", "A", "E"],
    description:
      "A small Andean lute (traditionally armadillo-shell) with all strings inside one octave — the sparkle of Andean folk.",
    song: "\"El Cóndor Pasa\" — Los Incas",
  },
  {
    id: "saz-baglama",
    name: "Saz / Bağlama",
    group: "world",
    midi: [47, 52, 57],
    spellings: ["B", "E", "A"],
    description:
      "Turkey's long-necked folk lute with microtonal, quarter-tone frets — the voice of the âşık poet-minstrels (many regional tunings).",
    song: "\"Uzun İnce Bir Yoldayım\" — Aşık Veysel",
  },
  {
    id: "sitar",
    name: "Sitar",
    group: "world",
    midi: [36, 43, 48, 55, 60, 65],
    spellings: ["C", "G", "C", "G", "C", "F"],
    description:
      "India's long-necked lute with sympathetic strings — here as Sa–Pa drones in C with the Ma melody string on top (Kharaj-Pancham style). The pedals are meend: wide gliding pulls up to a full fifth.",
    song: "\"Norwegian Wood\" — The Beatles",
  },
  {
    id: "cavaquinho",
    name: "Cavaquinho",
    group: "world",
    midi: [62, 67, 71, 74],
    spellings: ["D", "G", "B", "D"],
    description:
      "A small Brazilian 4-string (open G) — the rhythmic-harmonic engine of samba and choro.",
    song: "\"Brasileirinho\" — Waldir Azevedo",
  },
  {
    id: "ukulele",
    name: "Ukulele",
    group: "world",
    midi: [67, 60, 64, 69],
    spellings: ["G", "C", "E", "A"],
    description:
      "The classic re-entrant soprano/concert uke tuning, with a high g.",
    song: "\"Over the Rainbow\" — Israel Kamakawiwoʻole",
    reentrant: true,
  },
  {
    id: "baritone-uke",
    name: "Baritone Uke",
    group: "world",
    midi: [50, 55, 59, 64],
    spellings: ["D", "G", "B", "E"],
    description:
      "Tuned like a guitar's top four strings, an octave below a soprano uke — warm and mellow. Favoured in jazz and folk (e.g. Lyle Ritz).",
  },
  {
    id: "cuatro",
    name: "Cuatro",
    group: "world",
    midi: [69, 62, 66, 59],
    spellings: ["A", "D", "F♯", "B"],
    description:
      "Venezuela's 4-string (re-entrant) — the rhythmic-harmonic base of joropo and música llanera.",
    song: "\"Alma Llanera\" (Venezuela's unofficial anthem)",
    key: { root: "D", scale: "Major" },
    reentrant: true,
  },
  {
    id: "balalaika",
    name: "Balalaika",
    group: "world",
    midi: [64, 64, 69],
    spellings: ["E", "E", "A"],
    description:
      "Russia's triangular folk lute, played with the fingers.",
    song: "\"Kalinka\" (traditional)",
    key: { root: "A", scale: "Major" },
  },
  {
    id: "banjo",
    name: "Banjo",
    group: "world",
    midi: [50, 55, 59, 62, 67],
    spellings: ["D", "G", "B", "D", "G"],
    description:
      "A re-entrant 5-string with a high drone — the bluegrass sound.",
    song: "\"Foggy Mountain Breakdown\" — Earl Scruggs",
  },
  {
    id: "ps-e9-nashville",
    name: "E9 Nashville",
    group: "pedal-steel",
    midi: [47, 50, 52, 54, 56, 59, 64, 68, 63, 66],
    spellings: ["B", "D", "E", "F♯", "G♯", "B", "E", "G♯", "D♯", "F♯"],
    description:
      "THE country pedal-steel tuning — the crying, gliding sound you picture when you think \"pedal steel\" (Bud Isaacs, Buddy Emmons).",
    song: "\"Slowly\" — Webb Pierce (Bud Isaacs, 1954)",
    key: { root: "E", scale: "Major" },
    copedent: "e9",
    reentrant: true,
  },
  {
    id: "ps-e9-lanois",
    name: "E9 Lanois",
    group: "pedal-steel",
    midi: [47, 47, 52, 52, 56, 59, 64, 68, 63, 66],
    spellings: ["B", "B", "E", "E", "G♯", "B", "E", "G♯", "D♯", "F♯"],
    description:
      "ambient variant · doubled low strings for 12-string shimmer",
    key: { root: "E", scale: "Major" },
    copedent: "e9",
    reentrant: true,
  },
  {
    id: "ps-c6-swing-jazz",
    name: "C6 Swing/Jazz",
    group: "pedal-steel",
    midi: [48, 53, 57, 60, 64, 67, 69, 72, 76, 86],
    spellings: ["C", "F", "A", "C", "E", "G", "A", "C", "E", "D"],
    description:
      "The \"back neck\" of a double-neck pedal steel — used for western swing and jazz's fuller chord voicings (Buddy Emmons, Cindy Cashdollar).",
    song: "western swing — Bob Wills; jazz steel — Buddy Emmons",
    key: { root: "C", scale: "Major" },
    copedent: "c6",
  },
  {
    id: "ps-b6-universal",
    name: "B6 Universal",
    group: "pedal-steel",
    midi: [47, 50, 50, 54, 56, 59, 62, 68, 75, 78],
    spellings: ["B", "D", "D", "F♯", "G♯", "B", "D", "G♯", "D♯", "F♯"],
    description:
      "Jeff Newman's single-neck tuning that fuses the E9 (country) and C6 (jazz/swing) necks, so one neck covers both.",
    key: { root: "B", scale: "Major" },
    copedent: "e9",
  },
];

export const GROUP_ORDER: TuningGroup[] = [
  'lap-steel',
  'open',
  'pedal-steel',
  'common',
  'drop',
  'artist',
  'mode',
  'world',
];

export const GROUP_LABELS: Record<TuningGroup, string> = {
  'lap-steel': 'Lap steel',
  open: 'Open majors',
  'pedal-steel': 'Pedal steel',
  common: 'Guitar — common',
  drop: 'Guitar — drop',
  artist: 'Artist tunings',
  mode: 'Modal (white keys)',
  world: 'World instruments',
};

export const DEFAULT_TUNING_ID = 'c6';
export const CUSTOM_TUNING_ID = 'custom';

/** Sanity bounds for the custom tuning editor (E1 … C7). */
export const CUSTOM_MIDI_MIN = 28;
export const CUSTOM_MIDI_MAX = 96;
export const MIN_STRINGS = 3;
export const MAX_STRINGS = 10;

const BY_ID = new Map(TUNINGS.map((t) => [t.id, t]));

export function getTuning(id: string): Tuning | undefined {
  return BY_ID.get(id);
}
